### ISSUE TITLE
BS0.2整合

### ISSUE THREAD

**Issue by evolzed** [evolzed/armlogic#80]
### Objective:
Package ImageProcess and Track into single folder: /BS0.2

### Flowchart:
![BS0 2_FC](https://user-images.githubusercontent.com/35356984/75314950-37a62800-589c-11ea-8a0f-771a08b962f8.png)

### Todo:

Main:
- [x] Run using camera feed
- [x] Process according to flowchart
- [ ] average computational time <50ms

Vision:
- [x] BGLearn run as normal
- [x] Restart BGLearn if requested by signal
- [x] Crop individual bottle and send to YOLO
- [x] Able to support at least 20 bottles crop outs in a frame
- [x] Yolo correctly identify bottle from image and return results to vision
- [x] BottleDict value generated and stored
- [x] merge dataDict and centerlist
- [x] calcutle the actual pixel velocity
- [x] merge centerlist and centerList
- [x] upgrade image track to cooperate track
- [x] not set uplimit count of vision track bottlles 

Yolo:
- [x] Update and load newest version of CNN
- [x] Output correct results from pic given by imgprocess

Target:
- [x] Unique ID for each bottle identified
- [x] Get speed and position information from Vision
  - [ ] (Case 1: Only with detectObj) Get position information, then speed information calculated in track;
  - [x] (Case 2: with detectObj & trackObj) Get both position & speed information  
- [x] Request restart BGLearn if target is proven to be error (shadow or light reflection)
- [x] Estimate 9 counts and update positional data according to speed and time in between
- [x] TargetDict value generated and stored
- [x] The time interval in every loop could be set (30ms as in BS02)

Additional:
- [ ] Calculate probability of target ID getting mixed between frames while tracking.
- [ ] Depending on the certainty of target tracked, call ImageTrack, BGLearn, Yolo.

**Comment by evolzed** [comment]
@xiaobiky123  

ImageProcess功能及方案：

**Comment by evolzed** [comment]
@demoivrelu 

Track功能及方案：

预知问题：

所需时间：

**Comment by evolzed** [comment]
@xiaobiky123 @demoivrelu 
2/26日进程总结：

**Comment by evolzed** [comment]
@yuantao1880 

Track功能及方案：

测试标准：

预知问题：

所需时间：

**Comment by evolzed** [comment]
> @yuantao1880
> 
> Yolo功能及方案：目标类别22类，标号0-21,对输入的图像可以进行准确识别,返回物体的位置信息及类别
> 
> 测试标准：测试物体的识别类别是否准确，位置是否有偏差，运行时间预计60-100ms
> 
> 预知问题：需要筛选出可以使用的图像并处理22类别的瓶子透明背景图像，每个类别预计10张，前期需要220个瓶子透明背景的图像。时间上，需要有人帮忙处理数据，加上数据量大一些训练时间的周期比平常要长
> 
> 所需时间：处理出全部22类别的瓶子数据还需要大概2d，训练时间依电脑性能预计2d

所需时间只是整合BS0.2功能所需时间，Yolo的数据处理及训练在相应的Issue里说明。
需从新规划所需时间，暂定2天如何？

**Comment by xiaobiky123** [comment]
添加了cropBgBoxToYolo，功能是从背景学习中得到的目标剪切出来给YOLO，detectObjNotRelyLK

**Comment by xiaobiky123** [comment]
分割图片是每张图片 39毫秒
整张图片是一张图片42毫秒 所以 采用整张图片

**Comment by xiaobiky123** [comment]
新复制一份儿track.py 为track_hj_test.py 帮助小鲁一起调试，修改了计数方法和循环间隔，可以找到targetdict的跳变 15424d78f9534c6dba35ba8f254e51f686059de5

**Comment by xiaobiky123** [comment]
2020/3/2  任务更新 新任务如下：
1. 合并dataDict 和 centerList，让跟踪模块提取数据更方便
2. 对centerList的像素位移补充除以时间后的像素速度

**Comment by evolzed** [comment]
@demoivrelu 今天的进度更新？

**Comment by xiaobiky123** [comment]
进一步完善了 合并datadict和centerlist,在图像跟踪流程中给出了每个瓶子的瞬时位移，和除以时间后的瞬时速度，现在让detect得出用于检测的中心点和ID，以及用于图像跟踪的中心点和图像跟踪的ID，然后跟踪可以一直跟着detect得出的用于图像跟踪的点和ID，现在就剩下怎么和小鲁一起组合应用这些流程，让detect能一直检测，然后让跟踪能在一定时机使用。并且能搞清楚跟踪的瓶子和实时detect的瓶子的关系  3d0e021bee519e7f7df3ed1d084ca26ec229bdb9

**Comment by xiaobiky123** [comment]
修正了detect里的bug 为dataDict增加了detect的时间点，图像跟踪不再设定跟踪瓶子的上限，检测多少跟踪多少，同时增加了随时可以回到检测状态的模拟开关，可以随时更新检测状态，所以现在如何跟踪和检测并行，我认为就是检测，然后跟踪少量的时间，得到ID号，然后即时启动检测，融合之前跟踪的ID 和新的ID，更新ID b645d0fbd4477d4da1a651fa181d2c6113a3f6d4

**Comment by evolzed** [comment]
运行时间测试：

**Comment by xiaobiky123** [comment]
研究瓶子消失后LK跟踪的返回值，开发新的触发机制

**Comment by xiaobiky123** [comment]
为图像跟踪增加了返回状态 代表图像跟踪接是否结束   ecb39db220114697d0f28cc19d809b0aab2fdd29

**Comment by xiaobiky123** [comment]
开始开发将检测到的数据，融合到图像跟踪中，以实现随着瓶子增加，瓶子也被跟踪到，而且原有的ID还在，新的ID会新加给新来的瓶子，消失的瓶子的ID 会删除

**Comment by evolzed** [comment]
[System run time 运行时间测试](https://github.com/evolzed/armlogic/issues/98)

**Comment by xiaobiky123** [comment]
做了数据融合 检测和跟踪可以结合在一起，有多少瓶子跟踪多少瓶子，新进的瓶子会添加ID，旧的瓶子的ID不会更改  45229d44d0bbfe8fa390c4b5b4f982def363b4aa
